### PR TITLE
udpate

### PR DESCRIPTION
**Pull request by SaltFish001**
reWrite by ts
for nested route, I have to rewrite most functions in trouter.
next step:
 add bun build script. compile codes before publish

### CODE REVIEW

**Comment by jkyberneees** [comment]
Hi @SaltFish001 , thanks for your contributions. Can you run `bun run lint` to avoid linting changes? It's hard to review in this way. 

Regards

**Comment by SaltFish001** [comment]
> Hi @SaltFish001 , thanks for your contributions. Can you run `bun run lint` to avoid linting changes? It's hard to review in this way.您好，感谢您的贡献。你能运行 `bun run lint` 来避免 linting 变化吗？以这种方式很难审查。
> 
> Regards 问候

done
image

**Comment by jkyberneees** [comment]
> > Hi @SaltFish001 , thanks for your contributions. Can you run `bun run lint` to avoid linting changes? It's hard to review in this way.您好，感谢您的贡献。你能运行 `bun run lint` 来避免 linting 变化吗？以这种方式很难审查。
> > Regards 问候
> 
> done image

Thanks @SaltFish001, please push your local changes after running the linter.

**Comment by SaltFish001** [comment]
> > > Hi @SaltFish001 , thanks for your contributions. Can you run `bun run lint` to avoid linting changes? It's hard to review in this way.您好，感谢您的贡献。你能运行 `bun run lint` 来避免 linting 变化吗？以这种方式很难审查。
> > > Regards 问候
> > 
> > 
> > done image
> 
> Thanks @SaltFish001, please push your local changes after running the linter.

no change here.

**Comment by SaltFish001** [comment]
standard are not a good tools for TypeScript project. I will add eslint add prettire to this project

**Comment by SaltFish001** [comment]
Maybe I should publish my own branch to [JSR](https://jsr.io). I need this lib for my own projects.

**Pull request closed without merging**
